steps:
  - name: gcr.io/k8s-skaffold/pack
    env:
      - GOOGLE_FUNCTION_SIGNATURE_TYPE=$_FUNCTION_SIGNATURE_TYPE
      - GOOGLE_FUNCTION_TARGET=$_FUNCTION_TARGET
    args:
      - build
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--path=src'
      - '--env=GOOGLE_FUNCTION_SIGNATURE_TYPE'
      - '--env=GOOGLE_FUNCTION_TARGET'
    id: Buildpack
    entrypoint: pack
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DEPLOY_REGION: europe-west1
  _GCR_HOSTNAME: eu.gcr.io
  _PLATFORM: managed
  _IMAGE_NAME: functionsframeworkgolangmuxexample1
  _SERVICE_NAME: crhew1functionsframeworkgolangmuxexample1
  _FUNCTION_SIGNATURE_TYPE: http
  _FUNCTION_TARGET: EntryPoint
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - crhew1functionsframeworkgolangmuxexample1
  - functionsframeworkgolangmuxexample1